[package]
name = "hashbrown"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.39", features = ["derive"] }
env_logger = "0.11.8"
hex = "0.4.3"
log = "0.4.27"
md-5 = "0.10.6"
rayon = "1.10.0"
sha1 = "0.10.6"
sha2 = "0.10.9"
thiserror = "2.0.12"
